### ISSUE TITLE
Auto-completion for std:: types doesn't work with CXTranslationUnit_PrecompiledPreamble

### ISSUE THREAD

**Issue by ghost** [Sarcasm/irony-mode#4]
When `CXTranslationUnit_PrecompiledPreamble` option is used, auto-completion doesn't work for `std::` types.

How to reproduce:
- project-dir/.eproject

``` el
:includes '("src")
:extra-flags '("-std=c++11")
```
- project-dir/src/main.cpp

``` c++
#include <memory>

int foobar();

int main()
{
    ::foo       // <--- completion works
    std::auto_  // <--- no completion here
}
```

This fixes the situation for me:

``` diff
diff --git a/server/TUManager.cpp b/server/TUManager.cpp
index 8ccf472..6e0f482 100644
--- a/server/TUManager.cpp
+++ b/server/TUManager.cpp
@@ -51,8 +51,7 @@ CXTranslationUnit TUManager::parse(const std::string &              filename,
                                       filename.c_str(),
                                       argv, static_cast<int>(nbArgs),
                                       0, 0,
-                                      clang_defaultEditingTranslationUnitOptions()
-                                      | CXTranslationUnit_PrecompiledPreamble
+                                      (clang_defaultEditingTranslationUnitOptions() & ~CXTranslationUnit_PrecompiledPreamble)
                                       | CXTranslationUnit_CacheCompletionResults);
       delete [] argv;
       translationUnits_[filename] = tu;
```
- clang --version

```
Debian clang version 3.1-8 (branches/release_31) (based on LLVM 3.1)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

It seems that there was no such bug before I've updated clang from 3.0-6 to 3.1-8. However, if I'm not missing something, last version from Git no longer compiles with 3.0-6 and produces linker error:

```
undefined reference to `clang_getExpansionLocation'
```

Please tell me if I can provide some additional information.
