### ISSUE TITLE
irony-install-server fail after update 

### ISSUE THREAD

**Issue by AprilYL** [Sarcasm/irony-mode#531]
`In file included from /Users/***/.emacs.d/.cask/26.2/elpa/irony-20190515.2259/server/src/Command.cpp:11:
In file included from /Users/***/.emacs.d/.cask/26.2/elpa/irony-20190515.2259/server/src/Command.h:14:
/Users/april/.emacs.d/.cask/26.2/elpa/irony-20190515.2259/server/src/support/CIndex.h:12:10: fatal error: 
      'clang-c/Index.h' file not found
#include <clang-c/Index.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/irony-server.dir/Command.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/irony-server.dir/all] Error 2
make: *** [all] Error 2
`
I have try some way to solve it,but it still can't work.
sysyem: macOS Majave
emacs: 26-2
llvm: 8.0

**Comment by AprilYL** [comment]
I have solved this problem after update to 20190516
